package scrips.datamigration.reports.dto;

import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
public class JpaSssSecuritiesCodeDto {
	private String x_securities_code;
	private String y_securities_code;
	private String z_securities_code;
	private String x_issue_code;
	private String y_issue_code;
	private String z_issue_code;	
	private String x_description;
	private String y_description;
	private String z_description;
	private String x_securities_type_id;
	private String y_securities_type_id;
	private String z_securities_type_id;
	private String x_securities_status;
	private String y_securities_status;
	private String z_securities_status;
	private String x_securities_tenor_period_unit;
	private String y_securities_tenor_period_unit;
	private String z_securities_tenor_period_unit;
	private String x_currency_code;
	private String y_currency_code;
	private String z_currency_code;	
	private String x_denomination;
	private String y_denomination;
	private String z_denomination;
	private String x_issuer_id;
	private String y_issuer_id;
	private String z_issuer_id;	
	private String x_ipa;
	private String y_ipa;
	private String z_ipa;
	private String x_facility_eligibility_id;
	private String y_facility_eligibility_id;
	private String z_facility_eligibility_id;
	private String x_haircut_id;
	private String y_haircut_id;
	private String z_haircut_id;
	private String x_tradable;
	private String y_tradable;
	private String z_tradable;
	private String x_first_auction_date;
	private String y_first_auction_date;
	private String z_first_auction_date;
	private String x_first_issuance_date;
	private String y_first_issuance_date;
	private String z_first_issuance_date;
	private String x_first_issuance_amount;
	private String y_first_issuance_amount;
	private String z_first_issuance_amount;	
	private String x_redemption_date;
	private String y_redemption_date;
	private String z_redemption_date;
	private String x_optional_redemption_date;
	private String y_optional_redemption_date;
	private String z_optional_redemption_date;
	private String x_redemption_price;
	private String y_redemption_price;
	private String z_redemption_price;
	private String x_optional_redemption_price;
	private String y_optional_redemption_price;
	private String z_optional_redemption_price;
	private String x_central_bank_applied_amount;
	private String y_central_bank_applied_amount;
	private String z_central_bank_applied_amount;
	private String x_coupon_structure;
	private String y_coupon_structure;
	private String z_coupon_structure;
	private String x_coupon_payment_frequency;
	private String y_coupon_payment_frequency;
	private String z_coupon_payment_frequency;
	private String x_coupon_rate;
	private String y_coupon_rate;
	private String z_coupon_rate;
	private String x_average_yield;
	private String y_average_yield;
	private String z_average_yield;	
	private String x_day_count_convention;
	private String y_day_count_convention;
	private String z_day_count_convention;
	private String x_rounding_option;
	private String y_rounding_option;
	private String z_rounding_option;
	private String x_record_date_period;
	private String y_record_date_period;
	private String z_record_date_period;	
//	private String x_action;
//	private String y_action;
//	private String z_action;
//	private String x_status;
//	private String y_status;
//	private String z_status;
//	private String x_modified_by;
//	private String y_modified_by;
//	private String z_modified_by;
//	private String x_modified_date;
//	private String y_modified_date;
//	private String z_modified_date;	
//	private String x_approved_by;
//	private String y_approved_by;
//	private String z_approved_by;
//	private String x_approved_date;
//	private String y_approved_date;
//	private String z_approved_date;
//	private String x_created_date;
//	private String y_created_date;
//	private String z_created_date;
//	private String x_effective_date;
//	private String y_effective_date;
//	private String z_effective_date;	
//	private String x_approval_remark;
//	private String y_approval_remark;
//	private String z_approval_remark;
//	private String x_workflow_status_id;
//	private String y_workflow_status_id;
//	private String z_workflow_status_id;
	private String x_tenor_period;
	private String y_tenor_period;
	private String z_tenor_period;
	private String x_issue_price;
	private String y_issue_price;
	private String z_issue_price;
	private String x_issue_yield;
	private String y_issue_yield;
	private String z_issue_yield;
	private String x_redemption_reimburse;
	private String y_redemption_reimburse;
	private String z_redemption_reimburse;
	private String x_tax_scheme_id;
	private String y_tax_scheme_id;
	private String z_tax_scheme_id;
	private String x_first_coupon_date;
	private String y_first_coupon_date;
	private String z_first_coupon_date;
	private String x_benchmark_indicator;
	private String y_benchmark_indicator;
	private String z_benchmark_indicator;	
	private String y_remark;
}
