package scrips.datamigration.reports.dto;

import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
public class JpaSssAllotmentReportDto {
	private String x_id;
	private String y_id;
	private String z_id;
	private String x_securities_code;
	private String y_securities_code;
	private String z_securities_code;	
	private String x_auction_date;
	private String y_auction_date;
	private String z_auction_date;
	private String x_issuance_date;
	private String y_issuance_date;
	private String z_issuance_date;
	private String x_allotment_price;
	private String y_allotment_price;
	private String z_allotment_price;	
	private String x_total_nominal_amount_alloted;
	private String y_total_nominal_amount_alloted;
	private String z_total_nominal_amount_alloted;
	private String x_total_nominal_amount_to_be_alloted;
	private String y_total_nominal_amount_to_be_alloted;
	private String z_total_nominal_amount_to_be_alloted;
	private String x_first_allotment;
	private String y_first_allotment;
	private String z_first_allotment;	
	private String x_total_settlement_amount;
	private String y_total_settlement_amount;
	private String z_total_settlement_amount;
	private String x_processed;
	private String y_processed;
	private String z_processed;
	private String x_planned_total_nominal_amount_allotted;
	private String y_planned_total_nominal_amount_allotted;
	private String z_planned_total_nominal_amount_allotted;
	private String x_action;
	private String y_action;
	private String z_action;
	private String x_status;
	private String y_status;
	private String z_status;
	private String x_modified_by;
	private String y_modified_by;
	private String z_modified_by;
	private String x_modified_date;
	private String y_modified_date;
	private String z_modified_date;	
	private String x_approved_by;
	private String y_approved_by;
	private String z_approved_by;
	private String x_approved_date;
	private String y_approved_date;
	private String z_approved_date;
	private String x_created_date;
	private String y_created_date;
	private String z_created_date;
	private String x_effective_date;
	private String y_effective_date;
	private String z_effective_date;	
	private String x_approval_remark;
	private String y_approval_remark;
	private String z_approval_remark;
	private String x_workflow_status_id;
	private String y_workflow_status_id;
	private String z_workflow_status_id;
	private String y_remark;
}
