package scrips.datamigration.reports.dto;

import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
public class JpaSssTransactionDto {

	private String x_sss_reference;
	private String y_sss_reference;
	private String z_sss_reference;
	private String x_message_log_id;
	private String y_message_log_id;
	private String z_message_log_id;	
	private String x_securities_code;
	private String y_securities_code;
	private String z_securities_code;
	private String x_transaction_type;
	private String y_transaction_type;
	private String z_transaction_type;
	private String x_status;
	private String y_status;
	private String z_status;
	private String x_settlement_date;
	private String y_settlement_date;
	private String z_settlement_date;
	private String x_trade_date;
	private String y_trade_date;
	private String z_trade_date;
	private String x_currency_code;
	private String y_currency_code;
	private String z_currency_code;	
	private String x_settlement_amount;
	private String y_settlement_amount;
	private String z_settlement_amount;	
	private String x_nominal_amount;
	private String y_nominal_amount;
	private String z_nominal_amount;
	private String x_deal_price;
	private String y_deal_price;
	private String z_deal_price;
	private String x_deliverer_member_code;
	private String y_deliverer_member_code;
	private String z_deliverer_member_code;
	private String x_receiver_member_code;
	private String y_receiver_member_code;
	private String z_receiver_member_code;
	private String x_deliverer_rtgs_member_code;
	private String y_deliverer_rtgs_member_code;
	private String z_deliverer_rtgs_member_code;
	private String x_receiver_rtgs_member_code;
	private String y_receiver_rtgs_member_code;
	private String z_receiver_rtgs_member_code;
	private String x_deliverer_member_id;
	private String y_deliverer_member_id;
	private String z_deliverer_member_id;
	private String x_receiver_member_id;
	private String y_receiver_member_id;
	private String z_receiver_member_id;
	private String x_deliverer_account_id;
	private String y_deliverer_account_id;
	private String z_deliverer_account_id;	
	private String x_receiver_account_id;
	private String y_receiver_account_id;
	private String z_receiver_account_id;
	private String x_deliverer_rtgs_account;
	private String y_deliverer_rtgs_account;
	private String z_deliverer_rtgs_account;
	private String x_receiver_rtgs_account;
	private String y_receiver_rtgs_account;
	private String z_receiver_rtgs_account;
	private String x_repo_closing_date;
	private String y_repo_closing_date;
	private String z_repo_closing_date;
	private String x_repo_closing_settlement_amount;
	private String y_repo_closing_settlement_amount;
	private String z_repo_closing_settlement_amount;
	private String x_reason_code;
	private String y_reason_code;
	private String z_reason_code;		
	private String x_processed_date;
	private String y_processed_date;
	private String z_processed_date;
	private String x_created_date;
	private String y_created_date;
	private String z_created_date;
	private String x_modified_date;
	private String y_modified_date;
	private String z_modified_date;
	private String x_transaction_reference;
	private String y_transaction_reference;
	private String z_transaction_reference;
	private String x_sender_member_swift_code;
	private String y_sender_member_swift_code;
	private String z_sender_member_swift_code;
	private String x_payer_member_swift_code;
	private String y_payer_member_swift_code;
	private String z_payer_member_swift_code;
	private String x_payee_member_swift_code;
	private String y_payee_member_swift_code;
	private String z_payee_member_swift_code;
	private String x_receiver_member_swift_code;
	private String y_receiver_member_swift_code;
	private String z_receiver_member_swift_code;	
	private String x_sender_member_code;
	private String y_sender_member_code;
	private String z_sender_member_code;
	private String x_sender_type;
	private String y_sender_type;
	private String z_sender_type;
	private String x_accured_interest_amount;
	private String y_accured_interest_amount;
	private String z_accured_interest_amount;
	
//	private String x_grid_lock_indicator;
//	private String y_grid_lock_indicator;
//	private String z_grid_lock_indicator;
//	private String x_rollover_count;
//	private String y_rollover_count;
//	private String z_rollover_count;	
//	private String x_pending_cancellation_indicator;
//	private String y_pending_cancellation_indicator;
//	private String z_pending_cancellation_indicator;
//	private String x_payment_type;
//	private String y_payment_type;
//	private String z_payment_type;
	private String y_remark;
}
