package scrips.datamigration.sss.repository;

import java.util.Date;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import scrips.datamigration.reports.dto.JpaSssSecuritiesCodeDto;
import scrips.datamigration.sss.model.JpaSssSecuritiesCode;

@Repository
public interface SssSecuritiesCodeDAO extends JpaRepository<JpaSssSecuritiesCode, String> {

	JpaSssSecuritiesCode getBySecuritiesCode(String securitiesCode);

	JpaSssSecuritiesCode findBySecuritiesCode(String securitiesCode);

	@Query("select new scrips.datamigration.reports.dto.JpaSssSecuritiesCodeDto( case when x.securitiesCode is null then '' else x.securitiesCode end AS x_securities_code,\r\n"
			+ " case when y.securitiesCode is null then '' else y.securitiesCode end AS y_securities_code,\r\n"
			+ " case when z.securitiesCode is null then '' else  z.securitiesCode end AS z_securities_code,\r\n"
			+ " case when x.issueCode is null then '' else x.issueCode end AS x_issue_code,\r\n"
			+ " case when y.issueCode is null then '' else y.issueCode end AS y_issue_code,\r\n"
			+ " case when z.issueCode is null then '' else z.issueCode end AS z_issue_code,\r\n"
			+ " case when x.description is null then '' else x.description end AS x_description,\r\n"
			+ " case when y.description is null then '' else y.description end AS y_description,\r\n"
			+ " case when z.description is null then '' else z.description end AS z_description,\r\n"
			+ " case when x.securitiesTypeId is null then '' else x.securitiesTypeId end AS x_securities_type_id,\r\n"
			+ " case when y.securitiesTypeId is null then '' else y.securitiesTypeId end AS y_securities_type_id,\r\n"
			+ " case when z.securitiesTypeId is null then '' else z.securitiesTypeId end AS z_securities_type_id,\r\n"
			+ " case when x.securitiesStatus is null then '' else x.securitiesStatus end AS x_securities_status,\r\n"
			+ " case when y.securitiesStatus is null then '' else y.securitiesStatus end AS y_securities_status,\r\n"
			+ " case when z.securitiesStatus is null then '' else z.securitiesStatus end AS z_securities_status,\r\n"
			+ " case when x.securitiesTenorPeriodUnit is null then '' else x.securitiesTenorPeriodUnit end AS x_securities_tenor_period_unit,\r\n"
			+ " case when y.securitiesTenorPeriodUnit is null then '' else y.securitiesTenorPeriodUnit end AS y_securities_tenor_period_unit,\r\n"
			+ " case when z.securitiesTenorPeriodUnit is null then '' else z.securitiesTenorPeriodUnit end AS z_securities_tenor_period_unit,\r\n"
			+ " case when x.currencyCode is null then '' else x.currencyCode end AS x_currency_code,\r\n"
			+ " case when y.currencyCode is null then '' else y.currencyCode end AS y_currency_code,\r\n"
			+ " case when z.currencyCode is null then '' else z.currencyCode end AS z_currency_code,\r\n"
			+ " case when x.denomination is null then '' else x.denomination end AS x_denomination,\r\n"
			+ " case when y.denomination is null then '' else y.denomination end AS x_denomination,\r\n"
			+ " case when z.denomination is null then '' else z.denomination end AS x_denomination,\r\n"
			+ " case when x.issuerId is null then '' else x.issuerId end AS x_issuer_id,\r\n"
			+ " case when y.issuerId is null then '' else y.issuerId end AS y_issuer_id,\r\n"
			+ " case when z.issuerId is null then '' else z.issuerId end AS z_issuer_id,\r\n"
			+ " case when x.ipa is null then '' else x.ipa end AS x_ipa,\r\n"
			+ " case when y.ipa is null then '' else y.ipa end AS y_ipa,\r\n"
			+ " case when z.ipa is null then '' else z.ipa end AS z_ipa,\r\n"
			+ " case when x.facilityEligibilityId is null then '' else x.facilityEligibilityId end AS x_facility_eligibility_id,\r\n"
			+ " case when y.facilityEligibilityId is null then '' else y.facilityEligibilityId end AS y_facility_eligibility_id,\r\n"
			+ " case when z.facilityEligibilityId is null then '' else z.facilityEligibilityId end AS z_facility_eligibility_id,\r\n"
			+ " case when x.haircutId is null then '' else x.haircutId end AS x_haircut_id,\r\n"
			+ " case when y.haircutId is null then '' else y.haircutId end AS y_haircut_id,\r\n"
			+ " case when z.haircutId is null then '' else z.haircutId end AS z_haircut_id,\r\n"
			+ " case when x.tradable is null then '' else x.tradable end AS x_tradable,\r\n"
			+ " case when y.tradable is null then '' else y.tradable end AS y_tradable,\r\n"
			+ " case when z.tradable is null then '' else z.tradable end AS z_tradable,\r\n"
			+ " case when x.firstAuctionDate is null then '' else x.firstAuctionDate end AS x_first_auction_date,\r\n"
			+ " case when y.firstAuctionDate is null then '' else y.firstAuctionDate end AS y_first_auction_date,\r\n"
			+ " case when z.firstAuctionDate is null then '' else z.firstAuctionDate end AS z_first_auction_date,\r\n"
			+ " case when x.firstIssuanceDate is null then '' else x.firstIssuanceDate end AS x_first_issuance_date,\r\n"
			+ " case when y.firstIssuanceDate is null then '' else y.firstIssuanceDate end AS y_first_issuance_date,\r\n"
			+ " case when z.firstIssuanceDate is null then '' else z.firstIssuanceDate end AS z_first_issuance_date,\r\n"
			+ " case when x.firstIssuanceAmount is null then '' else x.firstIssuanceAmount end AS x_first_issuance_amount,\r\n"
			+ " case when y.firstIssuanceAmount is null then '' else y.firstIssuanceAmount end AS y_first_issuance_amount,\r\n"
			+ " case when z.firstIssuanceAmount is null then '' else z.firstIssuanceAmount end AS z_first_issuance_amount,\r\n"
			+ " case when x.redemptionDate is null then '' else x.redemptionDate end AS x_redemption_date,\r\n"
			+ " case when y.redemptionDate is null then '' else y.redemptionDate end AS y_redemption_date,\r\n"
			+ " case when z.redemptionDate is null then '' else z.redemptionDate end AS z_redemption_date,\r\n"
			+ " case when x.optionalRedemptionDate is null then '' else x.optionalRedemptionDate end AS x_optional_redemption_date,\r\n"
			+ " case when y.optionalRedemptionDate is null then '' else y.optionalRedemptionDate end AS y_optional_redemption_date,\r\n"
			+ " case when z.optionalRedemptionDate is null then '' else z.optionalRedemptionDate end AS z_optional_redemption_date,\r\n"
			+ " case when x.redemptionPrice is null then '' else x.redemptionPrice end AS x_redemption_price,\r\n"
			+ " case when y.redemptionPrice is null then '' else y.redemptionPrice end AS y_redemption_price,\r\n"
			+ " case when z.redemptionPrice is null then '' else z.redemptionPrice end AS z_redemption_price,\r\n"
			+ " case when x.optionalRedemptionPrice is null then '' else x.optionalRedemptionPrice end AS x_optional_redemption_price,\r\n"
			+ " case when y.optionalRedemptionPrice is null then '' else y.optionalRedemptionPrice end AS y_optional_redemption_price,\r\n"
			+ " case when z.optionalRedemptionPrice is null then '' else z.optionalRedemptionPrice end AS z_optional_redemption_price,\r\n"
			+ " case when x.centralBankAppliedAmount is null then '' else x.centralBankAppliedAmount end AS x_central_bank_applied_amount,\r\n"
			+ " case when y.centralBankAppliedAmount is null then '' else y.centralBankAppliedAmount end AS y_central_bank_applied_amount,\r\n"
			+ " case when z.centralBankAppliedAmount is null then '' else z.centralBankAppliedAmount end AS z_central_bank_applied_amount,\r\n"
			+ " case when x.couponStructure is null then '' else x.couponStructure end AS x_coupon_structure,\r\n"
			+ " case when y.couponStructure is null then '' else y.couponStructure end AS y_coupon_structure,\r\n"
			+ " case when z.couponStructure is null then '' else z.couponStructure end AS z_coupon_structure,\r\n"
			+ " case when x.couponPaymentFrequency is null then '' else x.couponPaymentFrequency end AS x_coupon_payment_frequency,\r\n"
			+ " case when y.couponPaymentFrequency is null then '' else y.couponPaymentFrequency end AS y_coupon_payment_frequency,\r\n"
			+ " case when z.couponPaymentFrequency is null then '' else z.couponPaymentFrequency end AS z_coupon_payment_frequency,\r\n"
			+ " case when x.couponRate is null then '' else x.couponRate end AS x_coupon_rate,\r\n"
			+ " case when y.couponRate is null then '' else y.couponRate end AS y_coupon_rate,\r\n"
			+ " case when z.couponRate is null then '' else z.couponRate end AS z_coupon_rate,\r\n"
			+ " case when x.averageYield is null then '' else x.averageYield end AS x_average_yield,\r\n"
			+ " case when y.averageYield is null then '' else y.averageYield end AS y_average_yield,\r\n"
			+ " case when z.averageYield is null then '' else z.averageYield end AS z_average_yield,\r\n"
			+ " case when x.dayCountConvention is null then '' else x.dayCountConvention end AS x_day_count_convention,\r\n"
			+ " case when y.dayCountConvention is null then '' else y.dayCountConvention end AS y_day_count_convention,\r\n"
			+ " case when z.dayCountConvention is null then '' else z.dayCountConvention end AS z_day_count_convention,\r\n"
			+ " case when x.roundingOption is null then '' else x.roundingOption end AS x_rounding_option,\r\n"
			+ " case when y.roundingOption is null then '' else y.roundingOption end AS y_rounding_option,\r\n"
			+ " case when z.roundingOption is null then '' else z.roundingOption end AS z_rounding_option,\r\n"
			+ " case when x.recordDatePeriod is null then '' else x.recordDatePeriod end AS x_record_date_period,\r\n"
			+ " case when y.recordDatePeriod is null then '' else y.recordDatePeriod end AS y_record_date_period,\r\n"
			+ " case when z.recordDatePeriod is null then '' else z.recordDatePeriod end AS z_record_date_period,\r\n"
//			+ " case when x.action is null then '' else x.action end AS x_action,\r\n"
//			+ " case when y.action is null then '' else y.action end AS y_action,\r\n"
//			+ " case when z.action is null then '' else z.action end AS z_action,\r\n"
//			+ " case when x.status is null then '' else x.status end AS x_status,\r\n"
//			+ " case when y.status is null then '' else y.status end AS y_status,\r\n"
//			+ " case when z.status is null then '' else z.status end AS z_status,\r\n "
//			+ " case when x.modifiedBy is null then '' else x.modifiedBy end AS x_modified_by,\r\n"
//			+ " case when y.modifiedBy is null then '' else y.modifiedBy end AS y_modified_by,\r\n"
//			+ " case when z.modifiedBy is null then '' else z.modifiedBy end AS z_modified_by,\r\n"
//			+ " case when x.modifiedDate is null then '' else x.modifiedDate end AS x_modified_date,\r\n"
//			+ " case when y.modifiedDate is null then '' else y.modifiedDate end AS y_modified_date,\r\n"
//			+ " case when z.modifiedDate is null then '' else z.modifiedDate end AS z_modified_date,\r\n"
//			+ " case when x.approvedBy is null then '' else x.approvedBy end AS x_approved_by,\r\n"
//			+ " case when y.approvedBy is null then '' else y.approvedBy end AS y_approved_by,\r\n"
//			+ " case when z.approvedBy is null then '' else z.approvedBy end AS z_approved_by,\r\n"
//			+ " case when x.approvedDate is null then '' else x.approvedDate end AS x_approved_date,\r\n"
//			+ " case when y.approvedDate is null then '' else y.approvedDate end AS y_approved_date,\r\n"
//			+ " case when z.approvedDate is null then '' else z.approvedDate end AS z_approved_date,\r\n "
//			+ " case when x.createdDate is null then '' else x.createdDate end AS x_created_date,\r\n"
//			+ " case when y.createdDate is null then '' else y.createdDate end AS y_created_date,\r\n"
//			+ " case when z.createdDate is null then '' else z.createdDate end AS z_created_date,\r\n"
//			+ " case when x.effectiveDate is null then '' else x.effectiveDate end AS x_effective_date,\r\n"
//			+ " case when y.effectiveDate is null then '' else y.effectiveDate end AS y_effective_date,\r\n"
//			+ " case when z.effectiveDate is null then '' else z.effectiveDate end AS z_effective_date,\r\n"
//			+ " case when x.approvalRemark is null then '' else x.approvalRemark end AS x_approval_remark,\r\n"
//			+ " case when y.approvalRemark is null then '' else y.approvalRemark end AS y_approval_remark,\r\n"
//			+ " case when z.approvalRemark is null then '' else z.approvalRemark end AS z_approval_remark,\r\n"
//			+ " case when x.workflowStatusId is null then '' else x.workflowStatusId end AS x_workflow_status_id,\r\n"
//			+ " case when y.workflowStatusId is null then '' else y.workflowStatusId end AS y_workflow_status_id,\r\n"
//			+ " case when z.workflowStatusId is null then '' else z.workflowStatusId end AS z_workflow_status_id,\r\n "
			+ " case when x.tenorPeriod is null then '' else x.tenorPeriod end AS x_tenor_period,\r\n"
			+ " case when y.tenorPeriod is null then '' else y.tenorPeriod end AS y_tenor_period,\r\n"
			+ " case when z.tenorPeriod is null then '' else z.tenorPeriod end AS z_tenor_period,\r\n "
			+ " case when x.issuePrice is null then '' else x.issuePrice end AS x_issue_price,\r\n"
			+ " case when y.issuePrice is null then '' else y.issuePrice end AS y_issue_price,\r\n"
			+ " case when z.issuePrice is null then '' else z.issuePrice end AS z_issue_price,\r\n"
			+ " case when x.issueYield is null then '' else x.issueYield end AS x_issue_yield,\r\n"
			+ " case when y.issueYield is null then '' else y.issueYield end AS y_issue_yield,\r\n"
			+ " case when z.issueYield is null then '' else z.issueYield end AS z_issue_yield,\r\n"
			+ " case when x.redemptionReimburse is null then '' else x.redemptionReimburse end AS x_redemption_reimburse,\r\n"
			+ " case when y.redemptionReimburse is null then '' else y.redemptionReimburse end AS y_redemption_reimburse,\r\n"
			+ " case when z.redemptionReimburse is null then '' else z.redemptionReimburse end AS z_redemption_reimburse,\r\n"
			+ " case when x.taxSchemeId is null then '' else x.taxSchemeId end AS x_tax_scheme_id,\r\n"
			+ " case when y.taxSchemeId is null then '' else y.taxSchemeId end AS y_tax_scheme_id,\r\n"
			+ " case when z.taxSchemeId is null then '' else z.taxSchemeId end AS z_tax_scheme_id,\r\n "
			+ " case when x.firstCouponDate is null then '' else x.firstCouponDate end AS x_first_coupon_date,\r\n"
			+ " case when y.firstCouponDate is null then '' else y.firstCouponDate end AS y_first_coupon_date,\r\n"
			+ " case when z.firstCouponDate is null then '' else z.firstCouponDate end AS z_first_coupon_date,\r\n"
			+ " case when x.benchmarkIndicator is null then '' else x.benchmarkIndicator end AS x_benchmark_indicator,\r\n"
			+ " case when y.benchmarkIndicator is null then '' else y.benchmarkIndicator end AS y_benchmark_indicator,\r\n"
			+ " case when z.benchmarkIndicator is null then '' else z.benchmarkIndicator end AS z_benchmark_indicator,\r\n"
			+ " case when z.remarks is null then case when y.remarks is null then '' else y.remarks end else z.remarks end AS y_remark)\r\n"
			+ " FROM JpaSssSecuritiesCodeSource z left join\r\n"
			+ " JpaSssSecuritiesCodeTemp y on z.id=y.id left join\r\n"
			+ " JpaSssSecuritiesCode x on y.securitiesCode=x.securitiesCode AND y.remarks is null where :date is null or DATE(z.migratedDate)= :date \r\n"
			+ " ORDER BY z.seq asc")
	List<JpaSssSecuritiesCodeDto> getReportData(@Param("date") Date date);

	@Query("select count(*) from JpaSssSecuritiesCodeTemp t inner join JpaSssSecuritiesCode l on l.securitiesCode=t.securitiesCode and t.remarks is null where :date is null or DATE(l.createdDate)= :date")
	Integer getMigratedCount(@Param("date") Date date);
}
